# GoReleaser Configuration for DeBros Network
# This config builds and publishes binaries and Debian packages

project_name: debros-network

env:
  - GO111MODULE=on

builds:
  # network-cli binary
  - id: network-cli
    main: ./cmd/cli
    binary: network-cli
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    
  # node binary
  - id: node
    main: ./cmd/node
    binary: node
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    
  # gateway binary
  - id: gateway
    main: ./cmd/gateway
    binary: gateway
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    
  # identity binary
  - id: identity
    main: ./cmd/identity
    binary: identity
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  # Tar.gz archives for each binary
  - id: binaries
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: DeBrosOfficial
    name: network
  draft: false
  prerelease: auto
  name_template: "Release {{.Version}}"
